version: "3.8"

services:
  frontend:
    build:
      context: ./invest-service-app
    ports:
      - "80:80"
    networks:
      - frontend
      - backend

  backend:
    image: kozlovva/invest-service
    depends_on:
      - mongodb
    ports:
    - 8080:8080
    networks:
      - backend
    environment:
      TINKOFF_SANDBOXTOKEN:
      SPRING_DATA_MONGODB_HOST: mongo

  mongodb:
    image: mongo:latest
    expose:
      - 27017
    ports:
      - 27017:27017
#    volumes:
#      - /Users/kozlovva/data/db:/data/db
    hostname: mongo
    networks:
      - backend

networks:
  frontend:
  backend: